export const website = [
    {
        id: 1,
        title: "Opedal's Portfolio",
        description: "Minimal portafolio black",
        image: "/images/web1.png",
        url: "https://opedal.vercel.app/",
        category: "Personal",
      
    },
    {
        id: 2,
        title: "Warp",
        description: "The intelligent terminal.",
        image: "/images/web2.png",
        url: "https://warp.dev/",
        category: "Company",
        
    },
    {
        id: 3,
        title: "Zed",
        description: "The editor for what's next",
        image: "/images/web3.png",
        url: "https://zed.dev/",
        category: "Company",
        
    },
    {
        id: 4,
        title: "Hyre",
        description: "Searching for a Star?",
        image: "/images/web4.png",
        url: "https://www.hyresearch.com/",
        category: "Company",
        
    },
    {
        id: 5,
        title: "Vercel",
        description: "Develop, deploy, and manage your serverless apps",
        image: "/images/web5.png",
        url: "https://vercel.com/",
        category: "Company",
        
    },
    {
        id: 6,
        title: "Render",
        description: "Your fastest path to production",
        image: "/images/web6.png",
        url: "https://render.com/",
        category: "Company",
        
    },
    {
        id: 7,
        title: "GitHub",
        description: " collaborative platform",
        image: "/images/web7.png",
        url: "https://github.com/",
        category: "Company",
        
    },
    {
        id: 8,
        title: "Naaseb",
        description: "Naaseb Portfolio",
        image: "/images/web8.png",
        url: "https://www.nazeeb.me/",
        category: "Personal",
    },
    {
        id: 9,
        title: "Gopidge",
        description: "Accelerate Your Market Intelligence",
        image: "/images/web9.png",
        url: "https://www.gopidge.com/",
        category: "Company",
    },
    {
        id: 10,
        title: "Modal",
        description: "High-performance, AI infrastructure",
        image: "/images/web10.png",
        url: "https://modal.com/",
        category: "Company",
    },
    {
        id: 11,
        title: "better Stack",
        description: " Radically better observability stack",
        image: "/images/web11.png",
        url: "https://betterstack.com/",
        category: "Company",
    },
    {
        id: 12,
        title: "lapz",
        description: "Watch Motorsports in AR",
        image: "/images/web12.png",
        url: "https://www.lapz.io",
        category: "3D",
    },
    {
        id: 13,
        title: "Yinger",
        description: "UI Engineer who dips his toes in Realtime 3D.",
        image: "/images/web13.png",
        url: "https://yinger.dev/",
        category: "3D",
    },
    {
        id: 14,
        title: "Flareum",
        description: "Desing System Builder",
        image: "/images/web14.png",
        url: "https://flareum.io/",
        category: "3D",
    },
    {
        id: 15,
        title: "ChainGPT",
        description: "Summarize the latest Crypto-related news.",
        image: "/images/web15.png",
        url: "https://www.chaingpt.org/",
        category: "3D",
    },
  
]